# Generated by Django 4.2.27 on 2025-12-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='last_mined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
