# Generated by Django 4.2.27 on 2025-12-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koin', '0002_alter_miner_last_mined'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='miner',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='koin.miner'),
        ),
    ]
