# Generated by Django 4.2.27 on 2026-01-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koin', '0005_remove_miner_referral_code_remove_miner_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='miner',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
