# Generated by Django 4.2.27 on 2026-01-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koin', '0009_boostpurchase_reference_boostpurchase_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostpurchase',
            name='multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
