# Generated by Django 4.2.27 on 2026-01-07 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koin', '0012_miner_custom_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinerRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('new_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_changes', to='koin.miner')),
            ],
            options={
                'ordering': ('-changed_at',),
            },
        ),
    ]
