# Generated by Django 4.2.27 on 2025-12-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koin', '0003_miner_referral_code_miner_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miner',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
