# Generated by Django 4.2.27 on 2026-01-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koin', '0008_boostpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostpurchase',
            name='reference',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='boostpurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='boostpurchase',
            name='tx_signature',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
