# Generated by Django 4.2.27 on 2026-01-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koin', '0011_solanawallet_boostpurchase_receiver_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='custom_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional custom base mining rate (units per second) for this user', max_digits=12, null=True),
        ),
    ]
