# Generated by Django 4.2.27 on 2026-01-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koin', '0013_minerratechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='is_mining',
            field=models.BooleanField(default=False),
        ),
    ]
